version: '3.7'

services:
  daemon:
    container_name: betabot_daemon
    image: bertytech/berty:latest
    restart: always
    entrypoint: sh
    #labels:
    #  com.centurylinklabs.watchtower.enable: "true"
    environment:
      - ANNOUNCE_SERVER
      - BERTY_STORE_DIR=/store/run
      - BERTY_NODE_NO_NOTIF=true
      - BERTY_NODE_LISTENERS=/ip4/0.0.0.0/tcp/9091
      - BERTY_P2P_IPFS_LISTENERS=/ip4/0.0.0.0/tcp/6001,/ip4/0.0.0.0/udp/6001/quic
      - BERTY_P2P_IPFS_ANNOUNCE=/ip4/${ANNOUNCE_SERVER}/tcp/6001,/ip4/${ANNOUNCE_SERVER}/udp/6001/quic
    command: -xec "berty daemon"
    volumes:
      - ./data/daemon:/store
    ports:
      - 6001:6001
      - 6001:6001/udp
    deploy:
     resources:
       limits:
         memory: 2000M
  bot:
    container_name: betabot_bot
    image: bertytech/berty:latest
    restart: always
    entrypoint: betabot
    links:
      - daemon
    #labels:
    #  com.centurylinklabs.watchtower.enable: "true"
    command:
      - -display-name=BetaBot
      - -addr=daemon:9091
      - "-staff-conversation-link=${BETABOT_STAFF_CONVERSATION_LINK}"
      - -store=/data/betabot.store
    depends_on:
      - daemon
    volumes:
      - ./data/betabot:/data
