"project_id" : "2"
"base_path" : "."
"base_url" : "https://berty.crowdin.com"

"commit_message": 'fix(i18n): new %language% translations


Signed-off-by: Crowdin <bots>'

"append_commit_message": false
"preserve_hierarchy": true

files: [
 {
  "source" : "/js/packages/berty-i18n/locale/en/messages.json",
  "translation" : "/js/packages/berty-i18n/locale/%two_letters_code%/%original_file_name%",
 }
]
