env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod download
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      #- darwin
      #- windows
    goarch:
      #- 386
      - amd64
      #- arm
      #- arm64
    dir: go/cmd/berty
    ignore:
      -
        goos: darwin
        goarch: 386
    flags:
      - "-a"
    ldflags:
      - '-extldflags "-static" -X berty.tech/berty/v2/go/pkg/bertymessenger.VcsRef=$(VCS_REF) -X berty.tech/berty/v2/go/pkg/bertymessenger.Version=$(VERSION) -X berty.tech/berty/v2/go/pkg/bertymessenger.BuildTime=$(BUILD_DATE)'
checksum:
  name_template: '{{.ProjectName}}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    -
      goos: windows
      format: zip
    wrap_in_directory: true
# generate .deb and .rpm (disabled for now)
#nfpms:
#  -
#    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
#    homepage:  https://github.com/berty/berty
#    description: "berty"
#    maintainer: "Berty Technologies <https://berty.tech>"
#    license: "Apache-2.0 OR MIT"
#    vendor: berty
#    formats:
#      - deb
#      - rpm
