linters:

  #golangcilint:
  #  config: .golangci.yml

  shellcheck:
    shell: bash

  # eslint:
  #  config: './client/react-native/.eslintrc'
  #  install_plugins: true

  swiftlint:

files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
    - 'experiment/*'
    - 'vendor/*'
    - '*.gen.*'
    - 'core/.scripts/upgrade-libp2p.sh'
    - 'network/.scripts/generate-logger.sh'
    - 'network/.scripts/upgrade-libp2p.sh'
    - 'client/android/ble/logger.sh'
    - 'client/ios/Reachability.swift'
fixers:
  enable: true
