linters:

  #golangcilint:
  #  config: .golangci.yml

  shellcheck:
    shell: bash

  # eslint:
  #  config: './client/react-native/.eslintrc'
  #  install_plugins: true

  swiftlint: {  }

files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
    - 'experiment/*'
    - 'vendor/*'
    - '*.gen.*'
fixers:
  enable: true
