version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.13
  docker:
    docker:
      - image: docker:18.06.3-ce-git

jobs:
  go-build:
    executor: golang
    steps:
      - checkout
      - run: echo "nothing to do"
  go-docker:
    executor: docker
    steps:
      - checkout
      - run: echo "nothing to do"

workflows:
  main:
    jobs:
      - go-build
      - go-docker
