
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5
  docker:  circleci/docker@0.5.13
  gotools: gotest/tools@0.0.10
  moul:    moul/build@1.12.1

jobs:
  go-build:
    working_directory: /go/src/berty.tech/go
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout:
          path: /go/src/berty.tech
      - moul/mod-download
      - gotools/mod-tidy-check
      - run: make install
      - run: make unittest
      - moul/install_golangci-lint
      - run: PATH=$PATH:$(pwd)/bin make lint
      - codecov/upload:
          file: coverage.txt
  go-docker:
    working_directory: /go/src/berty.tech/go
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout:
          path: /go/src/berty.tech
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/build:
          image: berty/berty
  go-generate:
    working_directory: /go/src/berty.tech
    docker:
      - image: bertytech/protoc:18
    steps:
      - checkout
      - run: find . -name gen.sum -delete
      - run: cd go && make generate_local && make tidy
      - run: cd docs && make generate_local
      - run: |
          git status | cat
          git diff -w | cat
          git diff-index -w --quiet HEAD --
  githooks:
    working_directory: /go/src/berty.tech
    docker:
      - image: bertytech/githooks:v1
    steps:
      - checkout
      - run: ./githooks/pre-commit
      - run: |
          git status | cat
          git diff -w | cat
          git diff-index -w --quiet HEAD --

  bazel-build:
    working_directory: /go/src/berty.tech
    docker:
      - image: bertytech/bazel:0.29.1-ubuntu-18.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel_build-v2-{{ .Branch }}
            - bazel_build-v2-
      - run: BAZEL_CMD_ARGS="--sandbox_debug --jobs=2 --local_ram_resources=HOST_RAM*.5" make bazel.build
      - run: ls -laR bazel-bin/*
      - save_cache:
          key: bazel_build-v2-{{ .Branch }}
          paths:
            - "/root/.cache/bazel"

  bazel-test:
    working_directory: /go/src/berty.tech
    docker:
      - image: bertytech/bazel:0.29.1-ubuntu-18.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel_test-v2-{{ .Branch }}
            - bazel_test-v2-
      - run: BAZEL_CMD_ARGS="--sandbox_debug --jobs=2 --local_ram_resources=HOST_RAM*.5" make bazel.test
      - save_cache:
          key: bazel_test-v2-{{ .Branch }}
          paths:
            - "/root/.cache/bazel"

  bazel-banner:
    working_directory: /go/src/berty.tech
    docker:
      - image: bertytech/bazel:0.29.1-ubuntu-18.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel_banner-v2-{{ .Branch }}
            - bazel_banner-v2-
      - run: BAZEL_CMD_ARGS="--sandbox_debug --jobs=2 --local_ram_resources=HOST_RAM*.5" make bazel.banner
      - save_cache:
          key: bazel_banner-v2-{{ .Branch }}
          paths:
            - "/root/.cache/bazel"

workflows:
  main:
    jobs:
      - go-build
      - go-docker
      - go-generate
      - githooks
      - bazel-build
      - bazel-test
      - bazel-banner
