steps:
  - label: android-build
    if: build.branch == "master" || (build.message !~ /\[skip android-build\]/ && build.message !~ /\[skip-ci\]/)
    plugins:
      - n0izn0iz/docker#v3.5.4:
          image: bitriseio/android-ndk:v2019_12_28-08_15-b1793
          propagate-uid-gid: true
          workdir: /home/buildkite-agent/go/src/berty.tech/berty
          environment:
            [
              "BUILDKITE=true",
              "GO111MODULE=on",
              "GOPATH=/home/buildkite-agent/go",
              "HOME=/home/buildkite-agent",
              "GRADLE_USER_HOME=/home/buildkite-agent/.gradle",
            ]
          volumes:
            [
              "/usr/local/go:/usr/local/go",
              "~:/home/buildkite-agent",
            ]
    agents:
      queue: "bigcores"
    commands:
      - set -x
      - export PATH=$$PATH:/home/buildkite-agent/go/bin
      - export PATH=/usr/local/go/bin:$$PATH
      - go version
      - cat tool/build/ci/.env >> js/.env
      - cd js
      - nice -n 10 make android.release
    artifact_paths:
      - "js/packages/berty-app/android/universal.apk"
      - "js/packages/berty-app/android/toc.pb"

  - label: ios-build
    if: build.branch == "master" || (build.message !~ /\[skip ios-build\]/ && build.message !~ /\[skip-ci\]/)
    agents:
      queue: "macos"
    plugins:
      - gopath-checkout#v1.0.1:
          import: berty.tech/berty
    commands:
      - set -x
      - export GYM_BUILDLOG_PATH=$$PWD/logs/$BUILDKITE_COMMIT
      - export PATH=$$(brew --prefix ruby)/bin:$$PATH # use brew ruby
      - cat tool/build/ci/.env >> js/.env
      - cd js
      - IOS_BUNDLE_ID=tech.berty.ios.yolo APP_SCHEME="Berty Yolo" IOS_RELEASE_METHOD=enterprise IOS_PROFILE=InHouse IOS_TEAM_ID=GR5463T564 nice -n 10 make ios.release
      - mv ./build/ios-Berty/development/Berty.ipa ../Berty-Yolo-$BUILDKITE_COMMIT.ipa
      # remove logs if succeed
      - rm -f $$PWD/logs/$BUILDKITE_COMMIT/*
    artifact_paths:
      - Berty-Yolo-$BUILDKITE_COMMIT.ipa
      - logs/$BUILDKITE_COMMIT/*
